# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

from pathlib import Path

import sphinx_rtd_theme  # noqa

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = u'OpenZFS'
copyright = u'%Y, OpenZFS'
html_last_updated_fmt = ''
author = u'OpenZFS'

# The short X.Y version
version = u''
# The full version, including alpha/beta/rc tags
release = u''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.githubpages',
    'sphinx.ext.intersphinx',
    'sphinx.ext.ifconfig',
    "sphinx_issues",
    "sphinx_rtd_theme",
    "notfound.extension",
    "sphinxext.rediraffe",
    "sphinx_last_updated_by_git",
    "sphinx_sitemap",
    "sphinx_llms_txt",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [u'_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# https://www.sphinx-doc.org/en/master/usage/extensions/ifconfig.html
# hide commands for tests in user documentation
def setup(app):
    app.add_config_value('zfs_root_test', default=True, rebuild='env')

zfs_root_test = False


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

html_baseurl = 'https://openzfs.github.io/openzfs-docs/'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'logo_only': True,
    'style_nav_header_background': '#29667e',
}

html_favicon = '_static/img/favicon.ico'

html_logo = '_static/img/logo/logo_main.png'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_context = {
    'css_files': [
        '_static/css/theme.css',  # set explicitly for local tests
        '_static/css/theme_overrides.css',  # override wide tables in RTD theme
        '_static/css/mandoc.css',
        ],
    'display_github': True,
    'github_user': 'openzfs',
    'github_repo': 'openzfs-docs',
    'github_version': 'master/docs/'
     }

html_js_files = [
    'js/redirect.js',
]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'OpenZFSdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'OpenZFS.tex', u'OpenZFS Documentation',
     u'OpenZFS', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'openzfs', u'OpenZFS Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'OpenZFS', u'OpenZFS Documentation',
     author, 'OpenZFS', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# GitHub repo
issues_github_path = "openzfs/zfs"

# equivalent to
issues_uri = "https://github.com/openzfs/zfs/issues/{issue}"
issues_pr_uri = "https://github.com/openzfs/zfs/pull/{pr}"
issues_commit_uri = "https://github.com/openzfs/zfs/commit/{commit}"

# Get absolute paths in 404
notfound_urls_prefix = '/openzfs-docs/'

# Redirects
rediraffe_redirects = {
    "Performance and Tuning/Async Write.rst": "Performance and Tuning/ZIO Scheduler.rst",
}

# Old man pages location -> to new master branch location
redirect_folders = {
    "man/1/": "man/master/1/",
    "man/4/": "man/master/4/",
    "man/5/": "man/master/5/",
    "man/7/": "man/master/7/",
    "man/8/": "man/master/8/",
}

# rediraffe doesn't support wildcards or regex, so fill redirects manually
for old, new in redirect_folders.items():
    for newpath in Path(new).rglob("**/*"):
        if newpath.suffix in [".rst"]:
            oldpath = str(newpath).replace(new, old, 1)
            rediraffe_redirects[oldpath] = str(newpath)

llms_txt_exclude = ["search", "genindex", "404", "_TableOfContents", "man/v*", "man/*index"]
